#!/bin/bash

#####################
# Autocomplete
#####################

# enable bash autocomplete
if command -v brew > /dev/null 2>&1; then
	BREW_PREFIX=$(brew --prefix)
	if [ -f ${BREW_PREFIX}/etc/bash_completion ]; then
	  . ${BREW_PREFIX}/etc/bash_completion
	fi
fi

# serverless
[ -f $HOME/node_modules/tabtab/.completions/serverless.bash ] \
    && . $HOME/node_modules/tabtab/.completions/serverless.bash
# sls
[ -f $HOME/node_modules/tabtab/.completions/sls.bash ] \
    && . $HOME/node_modules/tabtab/.completions/sls.bash

# gcloud
[ -f ${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc ] \
       && source ${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc
[ -f ${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc ] \
       && source ${BREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc

# Setup kubectl completion and completions for the alias 'k'
command -v kubectl > /dev/null 2>&1 && source <(kubectl completion bash | sed 's/kubectl/k/g')
# Setup autocompletion for kind cluster utility
command -v kind > /dev/null 2>&1 && source <(kind completion bash)
