#!/bin/bash

########################################
# History setup
########################################

export HISTSIZE=10000 # increase history size (default is 500)

HISTTIMEFORMAT='%F %T '
HISTFILESIZE=-1
HISTSIZE=-1
HISTCONTROL=ignoredups

# Custom history configuration
# Configure BASH to append (rather than overwrite the history):' 
shopt -s histappend

# Attempt to save all lines of a multiple-line command in the same entry' 
shopt -s cmdhist

# After each command, append to the history file and reread it' 
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$"\n"}history -a; history -c; history -r"