#!/bin/zsh

########################################
# History setup
########################################

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

bash_history_to_zsh_history() {
    awk '{print " :0:;"$1}' "$HOME/.bash_history" > "$HOME/.zsh_history"
}