#!/bin/zsh

export ZDOTDIR="$DOTFILES_LOCATION/.zprezto"
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

tee -a "$HOME/.zshrc" <<EOF
export ZDOTDIR="${ZDOTDIR}"

# Setup the .zprezto locations
source "${ZDOTDIR}/.zprezto/init.zsh"

source \${DOTFILES_LOCATION}/shell/profile
source \${DOTFILES_LOCATION}/shell/zsh/history
source \${DOTFILES_LOCATION}/shell/zsh/aliases

EOF